### ISSUE TITLE
Python + Cement

### ISSUE THREAD

**Issue by gau1991** [rtCamp/cli#7]
Features MVC architecture :
http://builtoncement.org/

**Comment by harshadyeola** [comment]
Easy Plugin Architecture

**Comment by rahul286** [comment]
Does it make it easy to implement **subcommands**, arguments and options parsing?

**Comment by harshadyeola** [comment]
Yes, Its Easy to make any level subcommands.
Also can make new command as plugin.

**Comment by rahul286** [comment]
Good. Let me know when demo code is completed.

**Comment by rahul286** [comment]
Have a look at http://cement.readthedocs.org/en/latest/examples/bash_auto_completion/

and https://github.com/datafolklabs/cement/issues/248

There are some issues surrounding autocompletion
