### ISSUE TITLE
Nodejs + commander argument handling takes too much efforts

### ISSUE THREAD

**Issue by harshadyeola** [rtCamp/cli#8]
When we pass args to command we need to apply checks manually on
- number of arguments
- argument type like number or string
  like 

``` bash
# Here we are checking no. of args should not be zero
# but we need to check max no. of args also
if (!pkgs.length) {
  console.error('packages required');
  process.exit(1);
}
```

**Comment by rahul286** [comment]
Did you search for libraries?

There must be other libs to take care of that.

**Comment by rahul286** [comment]
See https://www.npmjs.org/package/validator

http://validatejs.org/

Also:

https://nodejsmodules.org/tags/validation
https://nodejsmodules.org/tags/sanitize
https://nodejsmodules.org/tags/commander

Off-topic: https://www.npmjs.org/package/inquirer (for interactive projects)
